# Generated by Django 5.2 on 2025-05-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_publication_status', 'Can edit publication status')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
